version: "3.9"
services:
  showcase-psql-dev:
    image: postgres:16.2
    container_name: showcase-psql-dev
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: showcase
      POSTGRES_USER: showcase
      POSTGRES_PASSWORD: showcase
    networks:
      - showcase-dev-net
networks:
  showcase-dev-net:
