version: '3.9'

services:
  showcase-liquibase:
    container_name: showcase-liquibase
    image: liquibase/liquibase
    command: update
    volumes:
      - ./migrations/changelog.sql:/liquibase/changelog.sql
    networks:
      - tsc-monorepo-template_showcase-dev-net
    env_file: .env
    environment:
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.sql
networks:
  tsc-monorepo-template_showcase-dev-net:
    external: true
